project_name: classifcation
run_name: experiment_01

hyperparameters:
  random_forest:
    max_depth: [3, 7]
    min_samples_split: [5, 8]

  xgboost:
    max_depth: [3, 6, 10]
    min_child_weight: [1, 3, 8]
    #reg_alpha: [1, 3, 5]
    #reg_lambda: [1, 3, 5]